//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( VariablesAndFunctions() )*
 * f1 -> PMain()
 * f2 -> ( VariablesAndFunctions() )*
 * f3 -> <EOF>
 */
public class Goal implements Node {
   public NodeListOptional f0;
   public PMain f1;
   public NodeListOptional f2;
   public NodeToken f3;

   public Goal(NodeListOptional n0, PMain n1, NodeListOptional n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Goal(NodeListOptional n0, PMain n1, NodeListOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = new NodeToken("");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

