//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "?"
 * f1 -> Expression()
 * f2 -> ":"
 * f3 -> Expression()
 */
public class TernaryExpr implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeToken f2;
   public Expression f3;

   public TernaryExpr(NodeToken n0, Expression n1, NodeToken n2, Expression n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public TernaryExpr(Expression n0, Expression n1) {
      f0 = new NodeToken("?");
      f1 = n0;
      f2 = new NodeToken(":");
      f3 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

