//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( "*" )*
 * f1 -> Identifier()
 * f2 -> ( "[" Expression() "]" )*
 * f3 -> [ "=" Expression() ]
 */
public class ObjectType implements Node {
   public NodeListOptional f0;
   public Identifier f1;
   public NodeListOptional f2;
   public NodeOptional f3;

   public ObjectType(NodeListOptional n0, Identifier n1, NodeListOptional n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

