//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import helper.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */

public class Pass1<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   public GlobalSymTab g = new GlobalSymTab();

   public void print(String s) {
      System.out.print(s);
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      String _ret="";
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         _ret += " " + e.nextElement().accept(this,argu);
         _count++;
      }
      return (R)_ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( VariablesAndFunctions() )*
    * f1 -> PMain()
    * f2 -> ( VariablesAndFunctions() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> DeclarationStmt()
    *       | FunctionDeclaration()
    *       | StructDeclaration()
    *       | EnumDeclaration()
    *       | FunctionDefinition()
    *       | TypeDef()
    */
   public R visit(VariablesAndFunctions n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> BaseType()
    * f1 -> ObjectList()
    * f2 -> ";"
    */
   public R visit(DeclarationStmt n, A argu) {
      String _ret="";
      A param = argu;
      String type = n.f0.accept(this, argu).toString();
      _ret = type;
      if(argu!=null)
        param = (A)type;
      _ret += " " + n.f1.accept(this, param) + ";";
      n.f2.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> TypeSpecifier()
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> [ ArgList() ]
    * f4 -> ")"
    * f5 -> Block()
    */
   public R visit(FunctionDefinition n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String func_name = n.f1.accept(this, argu).toString();
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      g.add_function(func_name);

      n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      g.curr_func = null;

      return _ret;
   }

   /**
    * f0 -> TypeSpecifier()
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> [ ParameterList() ]
    * f4 -> ")"
    * f5 -> ";"
    */
   public R visit(FunctionDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( "," ParameterDeclaration() )*
    */
   public R visit(ParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> [ Identifier() ]
    */
   public R visit(ParameterDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <STRUCT>
    * f1 -> [ Identifier() ]
    * f2 -> "{"
    * f3 -> ( DeclarationStmt() )*
    * f4 -> "}"
    * f5 -> ";"
    */
   public R visit(StructDeclaration n, A argu) {
      String _ret="";
      String name=null;
      n.f0.accept(this, argu);
      int i;
      _ret = "struct";

      NodeOptional id = (NodeOptional)n.f1;
      if(id.present())
      {
        name = id.node.accept(this, argu).toString();
        _ret += " " + name;
      }

      NodeListOptional ns = (NodeListOptional)n.f3;
      _ret += " { ";
      if(ns.present())
      {
        for(i=0;i<ns.size();i++)
        {
          _ret += " " + ns.elementAt(i).accept(this, null).toString();
        }
      }
      _ret += " };";

      g.add_struct(name, _ret);

      return (R)_ret;
   }

   /**
    * f0 -> <TYPEDEF>
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> ";"
    */
   public R visit(TypeDef n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <ENUM>
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> Identifier()
    * f4 -> ( "," Identifier() )*
    * f5 -> "}"
    * f6 -> ";"
    */
   public R visit(EnumDeclaration n, A argu) {
      String _ret="", name=null;
      
      _ret = "enum";
      int i;
      
      name = n.f1.accept(this, argu).toString();
      _ret += " " + name;

      _ret += " { ";
      
      _ret += " " + n.f3.accept(this, argu).toString();

      NodeListOptional nlo = (NodeListOptional)n.f4;
      if(nlo.present())
      {
        for(i=0;i<nlo.size();i++)
        {
          _ret += ", " + ((NodeSequence)nlo.elementAt(i)).elementAt(1).accept(this, (A)"return");
        }
      }

      _ret += " };";

      g.add_enum(name, _ret);

      return (R)_ret;
   }

   /**
    * f0 -> MainReturnType()
    * f1 -> <MAIN>
    * f2 -> "("
    * f3 -> [ <INT> Identifier() "," <CHAR> "*" [ "*" ] Identifier() [ "[" "]" ] ]
    * f4 -> ")"
    * f5 -> Block()
    */
   public R visit(PMain n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String func_name = n.f1.toString();
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      g.add_function(func_name);

      n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      g.curr_func = null;

      return _ret;
   }

   /**
    * f0 -> BaseType()
    * f1 -> ( "*" )*
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> [ StorageClass() ]
    * f1 -> TypeSpecifier()
    */
   public R visit(BaseType n, A argu) {
      R _ret=null;
      String storage_class = "";
      if(n.f0.present())
        storage_class = n.f0.accept(this, argu).toString();
      String type = n.f1.accept(this, argu).toString();
      _ret = (R) (storage_class + " " + type);
      return _ret;
   }

   /**
    * f0 -> <STATIC>
    */
   public R visit(StorageClass n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> <INT>
    *       | <VOID>
    *       | <CHAR>
    *       | <SHORT>
    *       | <LONG>
    *       | <FLOAT>
    *       | <DOUBLE>
    *       | <SIGNED>
    *       | <UNSIGNED>
    *       | Identifier()
    *       | <STRUCT> [ Identifier() ] [ "{" ( DeclarationStmt() )* "}" ]
    *       | <ENUM> [ Identifier() ] "{" Identifier() ( "," Identifier() )* "}"
    */
   public R visit(TypeSpecifier n, A argu) {
      String _ret="";

      int i;

      if(n.f0.which<9)
      {
        _ret = n.f0.choice.toString();
      }
      else
      if(n.f0.which==9)
      {
        _ret = n.f0.choice.accept(this, argu).toString();
      }
      else
      if(n.f0.which==10)
      {
        _ret = "struct";

        NodeOptional id = (NodeOptional)((NodeSequence)n.f0.choice).elementAt(1);
        if(id.present())
        {
          _ret += " " + id.node.accept(this, argu).toString();
        }

        NodeOptional ndopt = (NodeOptional)((NodeSequence)n.f0.choice).elementAt(2);

        if(ndopt.present())
        {
          NodeListOptional ns = (NodeListOptional)((NodeSequence)ndopt.node).elementAt(1);
          _ret += " { ";
          for(i=0;i<ns.size();i++)
          {
            _ret += " " + ns.elementAt(i).accept(this, null).toString();
          }
          _ret += " } ";
        }
      }
      else
      if(n.f0.which==11)
      {
        _ret = "enum";

        NodeSequence ns = (NodeSequence)n.f0.choice;
        NodeOptional id = (NodeOptional)ns.elementAt(1);
        if(id.present())
        {
          _ret += " " + id.node.accept(this, argu).toString();
        }

        _ret += " { ";
        
        _ret += " " + ns.elementAt(3).accept(this, argu).toString();

        NodeListOptional nlo = (NodeListOptional)ns.elementAt(4);
        if(nlo.present())
        {
          for(i=0;i<nlo.size();i++)
          {
            _ret += ", " + ((NodeSequence)nlo.elementAt(i)).elementAt(1).accept(this, (A)"return");
          }
        }

        _ret += " } ";

      }

      return (R)_ret;
   }

   /**
    * f0 -> Arg()
    * f1 -> ( "," Arg() )*
    */
   public R visit(ArgList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> [ Identifier() ]
    */
   public R visit(Arg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INT>
    *       | <VOID>
    */
   public R visit(MainReturnType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ObjectType()
    * f1 -> ( "," ObjectType() )*
    */
   public R visit(ObjectList n, A argu) {
      String _ret=null;
      _ret = n.f0.accept(this, argu).toString() + " ";

      for(int i=0;i<n.f1.size();i++)
      {
        _ret += ", " + ((NodeSequence)n.f1.elementAt(i)).elementAt(1).accept(this, argu).toString();
      }

      return (R)_ret;
   }

   /**
    * f0 -> ( "*" )*
    * f1 -> Identifier()
    * f2 -> ( "[" Expression() "]" )*
    * f3 -> [ "=" Expression() ]
    */
   public R visit(ObjectType n, A argu) {
      String _ret="";

      // receives base type as string in argu
      // identifier serves as variable name
      // need to maintain original order in the declaration and assignments
      int i, array_level = 0, pointer_level = 0;
      String rhs = null, temp;

      if(n.f0.present()){
        pointer_level = n.f0.size();
        for(i=0;i<pointer_level;i++)
          _ret += "*";
      }

      String var_name = n.f1.accept(this, argu).toString();
      _ret += var_name;

      ArrayList<String> dimexpr = new ArrayList<String>();

      if(n.f2.present())
      {
        array_level = n.f2.size();
        for(i=0;i<array_level;i++)
        {
          temp = ((NodeSequence)n.f2.elementAt(i)).elementAt(1).accept(this, (A)"return").toString();
          _ret += "[" + temp + "]";
          dimexpr.add(temp);
        }
      }

      if(n.f3.present()){
        rhs = ((NodeSequence)n.f3.node).elementAt(1).accept(this, (A)"return").toString();
        _ret += "= " + rhs;
      }

      if(argu!=null)
        g.curr_func.put_variable(var_name, argu.toString(), pointer_level, array_level, dimexpr, rhs);

      return (R)_ret;
   }

   /**
    * f0 -> "{"
    * f1 -> StatementList()
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( [ Label() ] Statement() )*
    */
   public R visit(StatementList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ForLoop()
    *       | WhileLoop()
    *       | DoWhile()
    *       | Block()
    *       | IfStmt()
    *       | SwitchStmt()
    *       | BreakStmt()
    *       | ContinueStmt()
    *       | ReturnStmt()
    *       | DeclarationStmt()
    *       | Expression() ";"
    *       | GotoStmt()
    *       | ";"
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, (A)"not-struct");
      return _ret;
   }

   /**
    * f0 -> <GOTO>
    * f1 -> Label()
    * f2 -> ";"
    */
   public R visit(GotoStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ";"
    * f4 -> Expression()
    * f5 -> ";"
    * f6 -> Expression()
    * f7 -> ")"
    * f8 -> Statement()
    */
   public R visit(ForLoop n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <WHILE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileLoop n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <DO>
    * f1 -> Statement()
    * f2 -> <WHILE>
    * f3 -> "("
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public R visit(DoWhile n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <BREAK>
    * f1 -> ";"
    */
   public R visit(BreakStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <CONTINUE>
    * f1 -> ";"
    */
   public R visit(ContinueStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <RETURN>
    * f1 -> [ Expression() ]
    * f2 -> ";"
    */
   public R visit(ReturnStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IfThenElseStmt()
    *       | IfThenStmt()
    */
   public R visit(IfStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfThenStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> <ELSE>
    * f6 -> Statement()
    */
   public R visit(IfThenElseStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <SWITCH>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> "{"
    * f5 -> ( CaseStmt() )*
    * f6 -> "}"
    */
   public R visit(SwitchStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <CASE> Expression() ":" ( Statement() )*
    *       | <DFLT> ":" ( Statement() )*
    */
   public R visit(CaseStmt n, A argu) {
      R _ret=null;
      
      n.f0.accept(this, argu);

      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> ":"
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Ops()
    * f1 -> PrimaryExpr()
    */
   public R visit(BinOp n, A argu) {
      String _ret="";
      _ret = n.f0.accept(this, argu).toString();
      _ret += " " + n.f1.accept(this, argu).toString();
      return (R)_ret;
   }

   /**
    * f0 -> "||"
    *       | "&&"
    *       | "<"
    *       | "<="
    *       | ">"
    *       | ">="
    *       | "=="
    *       | "!="
    *       | "+"
    *       | "-"
    *       | "*"
    *       | "/"
    *       | "%"
    *       | "&"
    *       | "|"
    *       | "^"
    *       | "<<"
    *       | ">>"
    */
   public R visit(Ops n, A argu) {
      R _ret=null;
      _ret = (R)((NodeToken)n.f0.choice).tokenImage;
      return _ret;
   }

   /**
    * f0 -> "++"
    *       | "!"
    *       | "--"
    *       | "~"
    *       | "*"
    *       | "&"
    */
   public R visit(LeftUnary n, A argu) {
      R _ret=null;
      _ret = (R)n.f0.choice.toString();
      return _ret;
   }

   /**
    * f0 -> "++"
    *       | "--"
    */
   public R visit(RightUnary n, A argu) {
      R _ret=null;
      _ret = (R)((NodeToken)n.f0.choice).toString();
      return _ret;
   }

   /**
    * f0 -> PrimaryExpr() [ ExpressionContd() ]
    *       | LeftUnary() PrimaryExpr()
    */
   public R visit(Expression n, A argu) {
      String _ret="";
      if(n.f0.which==0)
      {
        _ret = ((NodeSequence)n.f0.choice).elementAt(0).accept(this, argu).toString();
        if(((NodeOptional)((NodeSequence)n.f0.choice).elementAt(1)).present())
          _ret += " " + ((NodeOptional)((NodeSequence)n.f0.choice).elementAt(1)).node.accept(this, argu).toString();
      }
      else
      {
        _ret = ((NodeSequence)n.f0.choice).elementAt(0).accept(this, argu).toString();
        _ret += " " + ((NodeSequence)n.f0.choice).elementAt(1).accept(this, argu).toString();
      }
      return (R)_ret;
   }

   /**
    * f0 -> RHSAssignExpr()
    *       | "(" [ Expression() ( "," Expression() )* ] ")"
    *       | BinOp()
    *       | RightUnary()
    *       | StructExpr()
    *       | ArrayLookup()
    *       | TernaryExpr()
    */
   public R visit(ExpressionContd n, A argu) {
      String _ret="";
      int i;
      if(n.f0.which==1)
      {
        _ret += " (";
        NodeOptional ndopt = (NodeOptional)((NodeSequence)n.f0.choice).elementAt(1);
        if(ndopt.present())
        {
          _ret += " " + ((NodeSequence)ndopt.node).elementAt(0).accept(this, (A)"return").toString();
          NodeListOptional nlo = (NodeListOptional)((NodeSequence)ndopt.node).elementAt(1);
          if(nlo.present())
          {
            for(i=0;i<nlo.size();i++)
            {
              _ret += ", "+((NodeSequence)nlo.elementAt(i)).elementAt(1).accept(this, (A)"return").toString();
            }
          }
        }
        _ret += " ) ";
      }
      else
        _ret += " " + n.f0.choice.accept(this, argu).toString();

      return (R)_ret;
   }

   /**
    * f0 -> "=" Expression()
    *       | "+=" Expression()
    *       | "-=" Expression()
    *       | "*=" Expression()
    *       | "/=" Expression()
    *       | "%=" Expression()
    *       | "<<=" Expression()
    *       | ">>=" Expression()
    *       | "&=" Expression()
    *       | "^=" Expression()
    *       | "|=" Expression()
    */
   public R visit(RHSAssignExpr n, A argu) {
      String _ret="";
      NodeSequence ns = (NodeSequence)n.f0.choice;
      _ret = ns.elementAt(0).toString() + " " + ns.elementAt(1).accept(this, (A)"return").toString();
      return (R)_ret;
   }

   /**
    * f0 -> "?"
    * f1 -> Expression()
    * f2 -> ":"
    * f3 -> Expression()
    */
   public R visit(TernaryExpr n, A argu) {
      String _ret="";
      n.f0.accept(this, argu);
      _ret = "?";
      _ret += " " + n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      _ret += ":";
      _ret += " " + n.f3.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> ( "[" PrimaryExpr() "]" )+
    */
   public R visit(ArrayLookup n, A argu) {
      String _ret="";
      for(int i=0;i<n.f0.size();i++)
      {
        _ret += "[" + ((NodeSequence)n.f0.elementAt(i)).elementAt(1).accept(this, (A)"return").toString() + "]";
      }
      return (R)_ret;
   }

   /**
    * f0 -> StructOps()
    * f1 -> Identifier()
    */
   public R visit(StructExpr n, A argu) {
      String _ret="";
      _ret = n.f0.accept(this, argu).toString();
      _ret += " " + n.f1.accept(this, argu).toString();
      return (R)_ret;
   }

   /**
    * f0 -> "->"
    *       | "."
    */
   public R visit(StructOps n, A argu) {
      R _ret=null;
      _ret = (R)((NodeToken)n.f0.choice).toString();
      return _ret;
   }

   /**
    * f0 -> Identifier()
    *       | "(" Expression() ")"
    *       | <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <STRING_LITERAL>
    *       | <CHARACTER_LITERAL>
    */
   public R visit(PrimaryExpr n, A argu) {
      R _ret=null;
      // n.f0.accept(this, argu);
      if(n.f0.which==0)
      {
        _ret = n.f0.choice.accept(this, argu);
      }
      else
      if(n.f0.which==1)
      {
        _ret = (R)(" ( " + ((NodeSequence)n.f0.choice).elementAt(1).accept(this, (A)"return").toString() + " ) ");
      }
      else
      {
        _ret = (R)n.f0.choice.toString();
      }

      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;
      _ret = (R)n.f0.toString();
      return _ret;
   }

}
