//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class Translator extends GJNoArguDepthFirst<String> {
   private boolean validParenthesis(String str) {
   		if (!(str.startsWith("(") && (str.endsWith(")")))
   			return false;
   		int count = 1;
   		int size = str.length() - 1;
   		int i = 0;
   		for (; i<size && count != 0; ++i) {
   			switch (str.charAt(i)) {
   				case '(':
   					++count;
   					break;
   				case ')':
   					--count;
   					break;
   			}
   		}
   		return i != size;
   }
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String visit(NodeList n) {
       String _ret="";
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         _ret += e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n) {
      if ( n.present() ) {
          String _ret="";
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            _ret += e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return "";
   }

   public String visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return "";
   }

   public String visit(NodeSequence n) {
       String _ret="";
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         _ret += e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n) { return n.tokenImage; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ExternalDeclaration() )+
    */
   public String visit(TranslationUnit n) {
       String _ret="";
      _ret = n.f0.accept(this);
      System.out.println(_ret);
      return _ret;
   }

   /**
    * f0 -> ( FunctionDefinition() | Declaration() )
    */
   public String visit(ExternalDeclaration n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> [ DeclarationSpecifiers() ]
    * f1 -> Declarator()
    * f2 -> [ DeclarationList() ]
    * f3 -> CompoundStatement()
    */
   public String visit(FunctionDefinition n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      _ret += " " + n.f2.accept(this);
      _ret += " " + n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> [ InitDeclaratorList() ]
    * f2 -> ";"
    */
   public String visit(Declaration n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      _ret += " " + n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( Declaration() )+
    */
   public String visit(DeclarationList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> StorageClassSpecifier() [ DeclarationSpecifiers() ]
    *       | TypeSpecifier() [ DeclarationSpecifiers() ]
    *       | TypeQualifier() [ DeclarationSpecifiers() ]
    */
   public String visit(DeclarationSpecifiers n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <AUTO> | <REGISTER> | <STATIC> | <EXTERN> | <TYPEDEF> )
    */
   public String visit(StorageClassSpecifier n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <VOID> | <CHAR> | <SHORT> | <INT> | <LONG> | <FLOAT> | <DOUBLE> | <SIGNED> | <UNSIGNED> | StructOrUnionSpecifier() | EnumSpecifier() | TypedefName() )
    */
   public String visit(TypeSpecifier n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <CONST> | <VOLATILE> )
    */
   public String visit(TypeQualifier n) {
       String _ret="";
      // _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> StructOrUnion()
    * f1 -> ( [ <IDENTIFIER> ] "{" StructDeclarationList() "}" | <IDENTIFIER> )
    */
   public String visit(StructOrUnionSpecifier n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <STRUCT> | <UNION> )
    */
   public String visit(StructOrUnion n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( StructDeclaration() )+
    */
   public String visit(StructDeclarationList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> InitDeclarator()
    * f1 -> ( "," InitDeclarator() )*
    */
   public String visit(InitDeclaratorList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> Declarator()
    * f1 -> [ "=" Initializer() ]
    */
   public String visit(InitDeclarator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> StructDeclaratorList()
    * f2 -> ";"
    */
   public String visit(StructDeclaration n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      _ret += " " + n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> TypeSpecifier() [ SpecifierQualifierList() ]
    *       | TypeQualifier() [ SpecifierQualifierList() ]
    */
   public String visit(SpecifierQualifierList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> StructDeclarator()
    * f1 -> ( "," StructDeclarator() )*
    */
   public String visit(StructDeclaratorList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( Declarator() | [ Declarator() ] ":" ConstantExpression() )
    */
   public String visit(StructDeclarator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <ENUM>
    * f1 -> ( [ <IDENTIFIER> ] "{" EnumeratorList() "}" | <IDENTIFIER> )
    */
   public String visit(EnumSpecifier n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> Enumerator()
    * f1 -> ( "," Enumerator() )*
    */
   public String visit(EnumeratorList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> [ "=" ConstantExpression() ]
    */
   public String visit(Enumerator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> [ Pointer() ]
    * f1 -> DirectDeclarator()
    */
   public String visit(Declarator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <IDENTIFIER> | "(" Declarator() ")" )
    * f1 -> ( "[" [ ConstantExpression() ] "]" | "(" ParameterTypeList() ")" | "(" [ IdentifierList() ] ")" )*
    */
   public String visit(DirectDeclarator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret +=  n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "*"
    * f1 -> [ TypeQualifierList() ]
    * f2 -> [ Pointer() ]
    */
   public String visit(Pointer n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      _ret += n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( TypeQualifier() )+
    */
   public String visit(TypeQualifierList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ParameterList()
    * f1 -> [ "," "..." ]
    */
   public String visit(ParameterTypeList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( "," ParameterDeclaration() )*
    */
   public String visit(ParameterList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> ( Declarator() | [ AbstractDeclarator() ] )
    */
   public String visit(ParameterDeclaration n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public String visit(IdentifierList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret +=  n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( AssignmentExpression() | "{" InitializerList() [ "," ] "}" )
    */
   public String visit(Initializer n) {
       String _ret="";
      _ret =  n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> Initializer()
    * f1 -> ( "," Initializer() )*
    */
   public String visit(InitializerList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret +=  n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> [ AbstractDeclarator() ]
    */
   public String visit(TypeName n) {
       String _ret="";
      _ret = n.f0.accept(this);
      String temp = n.f1.accept(this);
      if (!temp.isEmpty()) {
        _ret += " "+temp;
      }
      return _ret;
   }

   /**
    * f0 -> ( Pointer() | [ Pointer() ] DirectAbstractDeclarator() )
    */
   public String visit(AbstractDeclarator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( "(" AbstractDeclarator() ")" | "[" [ ConstantExpression() ] "]" | "(" [ ParameterTypeList() ] ")" )
    * f1 -> ( "[" [ ConstantExpression() ] "]" | "(" [ ParameterTypeList() ] ")" )*
    */
   public String visit(DirectAbstractDeclarator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret +=  n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(TypedefName n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( LabeledStatement() | Declaration() | ExpressionStatement() | CompoundStatement() | SelectionStatement() | IterationStatement() | JumpStatement() )
    */
   public String visit(Statement n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <IDENTIFIER> ":" Statement() | <CASE> ConstantExpression() ":" Statement() | <DFLT> ":" Statement() )
    */
   public String visit(LabeledStatement n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> [ Expression() ]
    * f1 -> ";"
    */
   public String visit(ExpressionStatement n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> [ DeclarationList() ]
    * f2 -> [ StatementList() ]
    * f3 -> "}"
    */
   public String visit(CompoundStatement n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += " " + n.f1.accept(this);
      _ret += " " + n.f2.accept(this);
      _ret += " " + n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( Statement() )+
    */
   public String visit(StatementList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <IF> "(" Expression() ")" Statement() [ <ELSE> Statement() ] | <SWITCH> "(" Expression() ")" Statement() )
    */
   public String visit(SelectionStatement n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <WHILE> "(" Expression() ")" Statement() | <DO> Statement() <WHILE> "(" Expression() ")" ";" | <FOR> "(" [ Expression() ] ";" [ Expression() ] ";" [ Expression() ] ")" Statement() )
    */
   public String visit(IterationStatement n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <GOTO> <IDENTIFIER> ";" | <CONTINUE> ";" | <BREAK> ";" | <RETURN> [ Expression() ] ";" )
    */
   public String visit(JumpStatement n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public String visit(Expression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> UnaryExpression() AssignmentOperator() AssignmentExpression()
    *       | ConditionalExpression()
    */
   public String visit(AssignmentExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ( "=" | "*=" | "/=" | "%=" | "+=" | "-=" | "<<=" | ">>=" | "&=" | "^=" | "|=" )
    */
   public String visit(AssignmentOperator n) {
      String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> LogicalORExpression()
    * f1 -> [ "?" Expression() ":" ConditionalExpression() ]
    */
   public String visit(ConditionalExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ConditionalExpression()
    */
   public String visit(ConstantExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> LogicalANDExpression()
    * f1 -> [ "||" LogicalORExpression() ]
    */
   public String visit(LogicalORExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> InclusiveORExpression()
    * f1 -> [ "&&" LogicalANDExpression() ]
    */
   public String visit(LogicalANDExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ExclusiveORExpression()
    * f1 -> [ "|" InclusiveORExpression() ]
    */
   public String visit(InclusiveORExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ANDExpression()
    * f1 -> [ "^" ExclusiveORExpression() ]
    */
   public String visit(ExclusiveORExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> EqualityExpression()
    * f1 -> [ "&" ANDExpression() ]
    */
   public String visit(ANDExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> RelationalExpression()
    * f1 -> [ ( "==" | "!=" ) EqualityExpression() ]
    */
   public String visit(EqualityExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ShiftExpression()
    * f1 -> [ ( "<" | ">" | "<=" | ">=" ) RelationalExpression() ]
    */
   public String visit(RelationalExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> AdditiveExpression()
    * f1 -> [ ( "<<" | ">>" ) ShiftExpression() ]
    */
   public String visit(ShiftExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> [ ( "+" | "-" ) AdditiveExpression() ]
    */
   public String visit(AdditiveExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> CastExpression()
    * f1 -> [ ( "*" | "/" | "%" ) MultiplicativeExpression() ]
    */
   public String visit(MultiplicativeExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ( "(" TypeName() ")" CastExpression() | UnaryExpression() )
    */
   public String visit(CastExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ( PostfixExpression() | "++" UnaryExpression() | "--" UnaryExpression() | UnaryOperator() CastExpression() | <SIZEOF> ( UnaryExpression() | "(" TypeName() ")" ) )
    */
   public String visit(UnaryExpression n) {
       String _ret="";
      _ret =  n.f0.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ( "&" | "*" | "+" | "-" | "~" | "!" )
    */
   public String visit(UnaryOperator n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ( "[" Expression() "]" | "(" [ ArgumentExpressionList() ] ")" | "." <IDENTIFIER> | "->" <IDENTIFIER> | "++" | "--" )*
    */
   public String visit(PostfixExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      if (!validParenthesis(_ret)) {
        _ret = "("+_ret+")";
      }
      return _ret;
   }

   /**
    * f0 -> ( <IDENTIFIER> | Constant() | "(" Expression() ")" )
    */
   public String visit(PrimaryExpression n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public String visit(ArgumentExpressionList n) {
       String _ret="";
      _ret = n.f0.accept(this);
      _ret += n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <CHARACTER_LITERAL>
    *       | <STRING_LITERAL>
    */
   public String visit(Constant n) {
       String _ret="";
      _ret = n.f0.accept(this);
      return _ret;
   }

}
